/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.lang.Math;
import domain.*;
import java.awt.Color;

/**
 *
 * @author mateo
 */
public class Ui extends javax.swing.JFrame {
    Numbers numberOne = new Numbers ();
    Numbers numberTwo = new Numbers();
    Numbers operador = new Numbers();



    /**
     * Creates new form Ui
     */
    public Ui() {
        initComponents();
        //Centrar la UI en la pantalla
        setLocationRelativeTo(null);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblScreenResult = new javax.swing.JLabel();
        btnNumberEight = new javax.swing.JButton();
        btnNumberSeven = new javax.swing.JButton();
        btnNumberFour = new javax.swing.JButton();
        btnNumberNine = new javax.swing.JButton();
        btnNumberOne = new javax.swing.JButton();
        btnNumberFive = new javax.swing.JButton();
        btnNumberSix1 = new javax.swing.JButton();
        btnNumberThree = new javax.swing.JButton();
        btnNumberTwo = new javax.swing.JButton();
        btnEqualityPotencia = new javax.swing.JButton();
        btnNumberZero1 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnSubtraction = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnPointDecimal = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblScreenOperation1 = new javax.swing.JLabel();
        btnEqualityValue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScreenResult.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblScreenResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblScreenResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1210, 70));

        btnNumberEight.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberEight.setText("8");
        btnNumberEight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberEightMouseClicked(evt);
            }
        });
        btnNumberEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberEightActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumberEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 220, 60));

        btnNumberSeven.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberSeven.setText("7");
        btnNumberSeven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberSevenMouseClicked(evt);
            }
        });
        btnNumberSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberSevenActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumberSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 220, 60));

        btnNumberFour.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberFour.setText("4");
        btnNumberFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberFourMouseClicked(evt);
            }
        });
        btnNumberFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberFourActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumberFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 220, 60));

        btnNumberNine.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberNine.setText("9");
        btnNumberNine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberNineMouseClicked(evt);
            }
        });
        btnNumberNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberNineActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumberNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 60));

        btnNumberOne.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberOne.setText("1");
        btnNumberOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberOneMouseClicked(evt);
            }
        });
        btnNumberOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberOneActionPerformed(evt);
            }
        });
        btnNumberOne.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnNumberOneKeyPressed(evt);
            }
        });
        getContentPane().add(btnNumberOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 220, 60));

        btnNumberFive.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberFive.setText("5");
        btnNumberFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberFiveMouseClicked(evt);
            }
        });
        btnNumberFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberFiveActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumberFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 220, 60));

        btnNumberSix1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberSix1.setText("6");
        btnNumberSix1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberSix1MouseClicked(evt);
            }
        });
        btnNumberSix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberSix1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumberSix1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 60));

        btnNumberThree.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberThree.setText("3");
        btnNumberThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberThreeMouseClicked(evt);
            }
        });
        btnNumberThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberThreeActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumberThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 220, 60));

        btnNumberTwo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberTwo.setText("2");
        btnNumberTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberTwoMouseClicked(evt);
            }
        });
        btnNumberTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumberTwoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumberTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 220, 60));

        btnEqualityPotencia.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnEqualityPotencia.setText("^");
        btnEqualityPotencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEqualityPotenciaMouseClicked(evt);
            }
        });
        getContentPane().add(btnEqualityPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 330, 100));

        btnNumberZero1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnNumberZero1.setText("0");
        btnNumberZero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumberZero1MouseClicked(evt);
            }
        });
        getContentPane().add(btnNumberZero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 420, 90));

        btnDivide.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnDivide.setText("/");
        btnDivide.setBorder(null);
        btnDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivideMouseClicked(evt);
            }
        });
        getContentPane().add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 360, 70));

        btnAdd1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnAdd1.setText("+");
        btnAdd1.setBorder(null);
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd1MouseClicked(evt);
            }
        });
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 360, 70));

        btnSubtraction.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnSubtraction.setText("-");
        btnSubtraction.setBorder(null);
        btnSubtraction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubtractionMouseClicked(evt);
            }
        });
        btnSubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractionActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtraction, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 360, 70));

        btnMultiply.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.setBorder(null);
        btnMultiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplyMouseClicked(evt);
            }
        });
        getContentPane().add(btnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 360, 70));

        btnPointDecimal.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnPointDecimal.setText(".");
        btnPointDecimal.setBorder(null);
        btnPointDecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPointDecimalMouseClicked(evt);
            }
        });
        getContentPane().add(btnPointDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 370, 110));

        btnClear.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnClear.setText("AC");
        btnClear.setBorder(null);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 440, 90));

        lblScreenOperation1.setBackground(new java.awt.Color(255, 51, 51));
        lblScreenOperation1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblScreenOperation1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblScreenOperation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1210, 70));

        btnEqualityValue.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnEqualityValue.setText("=");
        btnEqualityValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEqualityValueMouseClicked(evt);
            }
        });
        getContentPane().add(btnEqualityValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 330, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNumberEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberEightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberEightActionPerformed

    private void btnNumberSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberSevenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberSevenActionPerformed

    private void btnNumberFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberFourActionPerformed

    private void btnNumberNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberNineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberNineActionPerformed

    private void btnNumberOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberOneActionPerformed

    private void btnNumberFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberFiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberFiveActionPerformed

    private void btnNumberSix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberSix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberSix1ActionPerformed

    private void btnNumberThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberThreeActionPerformed

    private void btnNumberTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumberTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberTwoActionPerformed

    private void btnNumberNineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberNineMouseClicked
        // TODO add your handling code here for Nine Number:
        addNumber("9");
        
        
    }//GEN-LAST:event_btnNumberNineMouseClicked

    private void btnSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubtractionActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        System.out.println("Preesionando AC");
        lblScreenOperation1.setText("");
        lblScreenResult.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnNumberEightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberEightMouseClicked
        // TODO add your handling code here:
        addNumber("8");
    }//GEN-LAST:event_btnNumberEightMouseClicked

    private void btnNumberSevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberSevenMouseClicked
        // TODO add your handling code here:
        addNumber("7");
    }//GEN-LAST:event_btnNumberSevenMouseClicked

    private void btnNumberSix1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberSix1MouseClicked
        // TODO add your handling code here:
        addNumber("6");
    }//GEN-LAST:event_btnNumberSix1MouseClicked

    private void btnNumberFiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberFiveMouseClicked
        // TODO add your handling code here:
        addNumber("5");
    }//GEN-LAST:event_btnNumberFiveMouseClicked

    private void btnNumberFourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberFourMouseClicked
        // TODO add your handling code here:
        addNumber("4");
    }//GEN-LAST:event_btnNumberFourMouseClicked

    private void btnNumberThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberThreeMouseClicked
        // TODO add your handling code here:
        addNumber("3");
    }//GEN-LAST:event_btnNumberThreeMouseClicked

    private void btnNumberTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberTwoMouseClicked
        // TODO add your handling code here:
        addNumber("2");
    }//GEN-LAST:event_btnNumberTwoMouseClicked

    private void btnNumberOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberOneMouseClicked
        // TODO add your handling code here:
        addNumber("1");
    }//GEN-LAST:event_btnNumberOneMouseClicked

    private void btnNumberZero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumberZero1MouseClicked
        // TODO add your handling code here:
        addNumber("0");
    }//GEN-LAST:event_btnNumberZero1MouseClicked

    private void btnAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseClicked
        // TODO add your handling code here:
        numberOne.setNumberOne(Float.parseFloat(lblScreenOperation1.getText()));
        operador.setOperador("+");
        lblScreenOperation1.setText(""); 
    }//GEN-LAST:event_btnAdd1MouseClicked

    private void btnEqualityValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqualityValueMouseClicked
        // TODO add your handling code here:
        numberTwo.setSecondNumber(Float.parseFloat(lblScreenOperation1.getText()));
        if(null != operador.getOperador()) //De Acuerdo A que operacion se realice
        switch (operador.getOperador()) {
            case "+":
                lblScreenResult.setText(removeZero((float) (numberOne.getNumberOne() + numberTwo.getSecondNumber())));
                break;
            case "-":
                lblScreenResult.setText(removeZero((float) (numberOne.getNumberOne() - numberTwo.getSecondNumber())));
                break;
            case "*":
                lblScreenResult.setText(removeZero((float) (numberOne.getNumberOne() * numberTwo.getSecondNumber())));
                break;
            case "/":
                //Verificar que el divisor no sea igual a cero por que en cuyo caso no se podra efecturar la division
                if(numberTwo.getSecondNumber() == 0){
                    lblScreenResult.setText("!!ERROR No Es Posible Dividir Por Cero");
                }else{
                    lblScreenResult.setText(removeZero((float) (numberOne.getNumberOne() / numberTwo.getSecondNumber())));
                }
                //lblScreenResult.setText(Float.toString((float) (numberOne.getNumberOne() / numberTwo.getSecondNumber())));
                break;
            case "^":
                lblScreenResult.setText(removeZero((float) Math.pow(numberOne.getNumberOne(), numberTwo.getSecondNumber()))); //En donde dice removeZero, es la funcion para sacarle dos decimales a nuestro String en cuyo caso el numero sea .0, iria "Float.toString"
                break;
            default:
                break;
        }
            //Funcion para que se limpie la casilla de operaciones una vez se tenga el resultado en pantalla
            /*
            *Veroficar negando la preposicion en el if si la casilla de resultado no esta vacia, entonces setear la casilla de operacion vacia
            */
            if(!(lblScreenResult.getText().isEmpty())){
                lblScreenOperation1.setText("");
            }
    }//GEN-LAST:event_btnEqualityValueMouseClicked

    private void btnSubtractionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubtractionMouseClicked
        // TODO add your handling code here:
        numberOne.setNumberOne(Float.parseFloat(lblScreenOperation1.getText()));
        operador.setOperador("-");
        lblScreenOperation1.setText("");
    }//GEN-LAST:event_btnSubtractionMouseClicked

    private void btnMultiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplyMouseClicked
        // TODO add your handling code here:
        numberOne.setNumberOne(Float.parseFloat(lblScreenOperation1.getText()));
        operador.setOperador("*");
        lblScreenOperation1.setText("");
    }//GEN-LAST:event_btnMultiplyMouseClicked

    private void btnDivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivideMouseClicked
        // TODO add your handling code here:
        numberOne.setNumberOne(Float.parseFloat(lblScreenOperation1.getText()));
        operador.setOperador("/");
        lblScreenOperation1.setText("");
        
    }//GEN-LAST:event_btnDivideMouseClicked

    private void btnEqualityPotenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqualityPotenciaMouseClicked
        // TODO add your handling code here:
        numberOne.setNumberOne(Float.parseFloat(lblScreenOperation1.getText()));
        operador.setOperador("^");
        lblScreenOperation1.setText("");
        
    }//GEN-LAST:event_btnEqualityPotenciaMouseClicked

    private void btnPointDecimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPointDecimalMouseClicked
        // TODO add your handling code here:
        if(!(lblScreenOperation1.getText().contains("."))){
            lblScreenOperation1.setText(lblScreenOperation1.getText() + ".");
        }
    }//GEN-LAST:event_btnPointDecimalMouseClicked

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnNumberOneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnNumberOneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumberOneKeyPressed

    /**
     * @param args the command line arguments
     */
    //Funcion para quitar el .0 luego de que se realice una operacion con numeros enteros exactos
    public String removeZero(float resultado){
        String retorno = "";
        
        retorno = Float.toString(resultado);
        
        if(resultado%1==0){ //Si el resultado de la division del numero entre 1 da 0 es porque termina en .0 el numero decimal por lo que se ejecutara el codigo
            retorno = retorno.substring(0, retorno.length() -2 );   
        }
        
        return retorno;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ui().setVisible(true);
            }
        });

    }
    
    public void addNumber(String digito){
        lblScreenOperation1.setText(lblScreenOperation1.getText()+ digito);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEqualityPotencia;
    private javax.swing.JButton btnEqualityValue;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNumberEight;
    private javax.swing.JButton btnNumberFive;
    private javax.swing.JButton btnNumberFour;
    private javax.swing.JButton btnNumberNine;
    private javax.swing.JButton btnNumberOne;
    private javax.swing.JButton btnNumberSeven;
    private javax.swing.JButton btnNumberSix1;
    private javax.swing.JButton btnNumberThree;
    private javax.swing.JButton btnNumberTwo;
    private javax.swing.JButton btnNumberZero1;
    private javax.swing.JButton btnPointDecimal;
    private javax.swing.JButton btnSubtraction;
    private javax.swing.JLabel lblScreenOperation1;
    private javax.swing.JLabel lblScreenResult;
    // End of variables declaration//GEN-END:variables
    private boolean punto = true;
}

